import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";
import "../styles/_reset-css.css";
import "../styles/typing-theme.css";
import "./globals.css";
import { LayoutProvider } from "@/contexts/layoutStates";
import { CreateBoardProvider } from "@/contexts/createBoardStates";
import { NotifyProvider } from "@/contexts/notifyStates";
import { TypingThemeProvider } from "@/contexts/typingThemeStates";
import Providers from "./providers";

const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // adjust based on what you need
  variable: "--font-roboto-mono", // optional, for use in CSS
  display: "swap", // optional for better UX
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`fixed inset-0 text-primaryBlack`}>
        <Providers>
          <CreateBoardProvider>
            <NotifyProvider>
              <TypingThemeProvider>
                <LayoutProvider>
                  <div id="myportal" />
                  {children}
                </LayoutProvider>
              </TypingThemeProvider>
            </NotifyProvider>
          </CreateBoardProvider>
        </Providers>
      </body>
    </html>
  );
}
